### PR TITLE
Correct formula to compute sum of integers

### PR DESCRIPTION
**Pull request by steffkes**
the formula is missing the multiplier sign to actually work. otherwise you get an error:

```r
> n <- 100
> n(n+1)/2
Error in n(n + 1) : could not find function "n"
```

after this change:

```r
> n <- 100
> n * (n+1) / 2
[1] 5050
```

### CODE REVIEW

**Comment by rafalab** [comment]
Thanks!

**Comment by rafalab** [comment]
Actually I just realized this was a math equation not code. I am changing it back.

**Comment by steffkes** [comment]
I'm not sure I follow @rafalab - just using "as is" leads to a error message, so are you saying the fix needs to be something else?

**Comment by rafalab** [comment]
It’s math notation not meant to be copied and pasted as code. In the html you will see that we use different font for math formulas and code. Part of the exercise is to be able to write R code to compute what is give as a mathematical formula.

**Pull request merged**
